[build-system]
requires = ["setuptools>=51"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests/unit"]

[tool.coverage.run]
branch = true
source = ["epiweeks"]

[tool.coverage.paths]
source = ["src"]

[tool.black]
line-length = 80
target-version = ["py38", "py39", "py310", "py311", "py312"]

[tool.isort]
profile = "black"

[tool.pylint.reports]
score = false

[tool.pylint.format]
max-line-length = 80
expected-line-ending-format = "LF"

[tool.taskipy.tasks]
test = "task test_cov tests"
test_min = "pytest"
test_all = "pytest tests"
test_cov = "pytest --cov --cov-report=term-missing --cov-fail-under=100"
test_cov_html = "pytest --cov --cov-report=term --cov-report=html"
lint = "task lint_isort && task lint_black && task lint_pylint && task lint_mypy"
lint_isort = "isort --check-only src tests"
lint_black = "black --check --quiet src tests"
lint_pylint = "pylint src"
lint_mypy = "mypy src"
format = "isort src tests && black src tests"
upgrade = "task upgrade_dev && task upgrade_docs"
upgrade_dev = "pip install -U -r requirements-dev.txt"
upgrade_docs = "pip install -U -r docs/requirements.txt"
docs = "sphinx-build -E docs docs/_build"
